services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "5010:3000"
    volumes:
    - grafana_data:/var/lib/grafana
    - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards 
    - ./grafana/provisioning/alerting:/etc/grafana/provisioning/alerting
    - ./grafana/rules:/etc/grafana/rules
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    command:
      - '--config.expand-env=true'
    networks:
      - monitoring_net
    depends_on:
      - prometheus
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "5011:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring_net

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    networks:
      - monitoring_net

  mariadb_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mariadb_exporter
    environment:
      - DATA_SOURCE_NAME="exporter:exporter_password@(mariadb:3306)/"
    command:
      - "--mysqld.username=exporter:exporter_password"
      - "--mysqld.address=mariadb:3306"
    networks:
      - monitoring_net
      - lottery_lottery_net
    
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    container_name: cadvisor
    ports:
      - "5013:8080"
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /volume1/@docker/:/var/lib/docker:ro
      - /proc:/host/proc:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - monitoring_net

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml
    networks:
      - monitoring_net

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - monitoring_net
    depends_on:
      - loki

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring_net:
    driver: bridge
  lottery_lottery_net:
    external: true
