apiVersion: 1
contactPoints:
  - orgId: 1
    name: Slack
    receivers:
      - uid: fembpvf3w5zpce
        type: slack
        settings:
          url: ${SLACK_WEBHOOK_URL}
        disableResolveMessage: false
